### DISCUSSION TITLE
Sessions are lost after restarting the server

### DISCUSSION THREAD

**Discussion by diegocaprioli** [devlikeapro/waha#1056] [Q&A]
Hello,

I'm new to WAHA, and after a few days reading and testing, started coding my app using it. I got the WAHA Plus, and used it in my local dev env, and also in a testing/staging server online to try out a somewhat real scenario for installing and managing it. Both installations went well, and I started using it mainly in my local env for development.

In my local env I have WAHA Plus with the NOWEB Engine. I noted that after restarting the server, the session I was working with, no longer appears. I'm testing creating and authorizing sessions, and everything works well. When turning my local docker off for the day, and starting it again the next day to continue development, the session is lost. At creation time for the session, I have specified to use the storage, so I'm assuming that it should restart with the sessions that where there before the shutdown. Is this the expected behavior, right?

Any help or tips you could give are welcome!

This is a snippet of my docker-compose.yml for WAHA:

```
### WAHA ####################################
    waha:
      image: devlikeapro/waha-plus:latest  # Use WAHA Plus for local testing
      container_name: waha
      restart: always
      ports:
        - "127.0.0.1:3003:3000"  # Expose WAHA API locally on port 3000
      environment:
        - WHATSAPP_DEFAULT_ENGINE=NOWEB  # Switch to NOWEB for performance
        - WAHA_PRINT_QR=True  # Enable QR code for authentication
        - WHATSAPP_API_HOSTNAME=localhost
        - WHATSAPP_API_PORT=3000
        - WAHA_LOG_LEVEL=info  # Set to debug if issues arise
        - WAHA_WORKER_ID=waha_local
        - WAHA_BASE_URL=http://localhost:3003
        - WHATSAPP_FILES_LIFETIME=0
      volumes:
        - ./waha/sessions:/app/.sessions  # Store session data locally
        - ./waha/media:/app/.media  # Store media files locally
      networks:
        - backend
```

I can see the WAHA db files and more created for the sessions:

![Screenshot 2025-06-17 061712](https://github.com/user-attachments/assets/ea68a2f3-ff2a-4551-924b-966ada51d12e)

And this is the default configuration that the sessions I create receive every time (it's a PHP array that gets converted into json, but you'll get the idea):

```
        return [
            'start' => true,
            'config' => [
                'proxy' => null,
                'debug' => false,
                'noweb' => [
                    'store' => [
                        'enabled' => true,
                        'fullSync' => false,
                    ],
                ],
                'webhooks' => [
                    [
                        'url' => app()->environment() == 'local' ? "http://nginx:80/webhook/waha" : route('webhook.waha'),
                        'events' => ["session.status", "message", "message.any"],
                        'hmac' => null,
                        'retries' => [
                            'policy' => 'linear',
                            'delaySeconds' => 30,
                            'attempts' => 5
                        ],
                        'customHeaders' => [
                            [
                                'name' => "Host",
                                'value' => parse_url(route('webhook.waha'), PHP_URL_HOST),
                            ],
                        ],
                    ],
                ],
            ],
        ];
```

And this is how a session looks like in the WAHA Dashboard after it was created:

![Screenshot 2025-06-17 062923](https://github.com/user-attachments/assets/a6acf0b9-efff-4e6e-819f-670d67f8b30d)

Note the last notification in yellow below this last screeshot... Not sure if that is a clue for this, and if I have to do something about it.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
