### DISCUSSION TITLE
Volumes Question

### DISCUSSION THREAD

**Discussion by akitamostodos** [devlikeapro/waha#229] [Q&A] [answered]
Hello, I whant to know if its possible define volume to store data of this app, on other compose i define volume..... but on this I cant find the volunme where store the files.

Can i use similar this? ->

version: '3'
services:
  whatsapp-http-api4:
    image: devlikeapro/whatsapp-http-api
    container_name: whatsapp-http-api4
    ports:
      - "3001:3001/tcp"
    environment:
      # Environment variables from https://waha.devlike.pro/docs/how-to/config/
      - WHATSAPP_HOOK_URL=https://httpbin.org/post
      - WHATSAPP_HOOK_EVENTS=message
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
    volumes:
      - ./data/:/
    restart: always

Now I cant find the host volume where the data and sessions are stored.....

Thanks.

**Comment by allburov** [comment]
Hi! You should use it this way, so you can find the sessions' data in `./.sessions`

https://github.com/devlikeapro/whatsapp-http-api/blob/core/docker-compose.yaml#L20C1-L21C37

**Reply by allburov** [reply]
```yaml
    volumes:
      - "./.sessions:/app/.sessions"
```

**Reply by allburov** [reply, marked as answer]
btw, saving sessions information available only in PLUS version
```yaml
  whatsapp-http-api-plus:
    image: devlikeapro/whatsapp-http-api-plus
    container_name: whatsapp-http-api-plus
    ports:
      - "3000:3000/tcp"
    volumes:
      - "./.sessions:/app/.sessions"
```

https://waha.devlike.pro/docs/how-to/plus-version/
