### DISCUSSION TITLE
WAHA + Home Assistant

### DISCUSSION THREAD

**Discussion by Dbmsk** [devlikeapro/waha#231] [Q&A]
Need Assistance Connecting WAHA to Home Assistant

 I've been thoroughly impressed with WAHA and its capabilities. However, I find myself in a bit of a dilemma when it comes to connecting WAHA with my Home Assistant setup, specifically for sending notifications.

As much as I'd love to share a comprehensive guide on how to achieve this integration, I'm afraid I haven't been able to figure it out just yet. That's where I'm reaching out to this knowledgeable community for assistance.

If anyone has successfully connected WAHA to Home Assistant for notifications, I would greatly appreciate your guidance. Whether it's a step-by-step process, tips to troubleshoot potential issues, or even just pointing me in the right direction, any help would be invaluable.

I'm eager to learn from your experiences, and I believe your insights will not only benefit me but also others who might be facing a similar challenge.

Thank you all in advance for your time!

**Comment by allburov** [comment]
Hi! I'm not familiar with home automation, which assistant do you use?  Does it support any HTTP calls or webhooks?

**Comment by mmojadad** [comment]
Hi
I am interest too.

**Comment by RedWolf112** [comment]
I used this [tutorial ](https://community.simon42.com/t/whatsapp-und-ha-senden-und-empfangen-von-nachrichten/19807). But only the send function.
The rest command must look like this:
```
rest_command:
    whatsappsend:
        url: "http://192.168.xxx.xxx:3000/api/sendText"
        method: POST
        headers:
          accept: "application/json"
          X-Api-Key: "yourkey"
        payload: "{ \"chatId\": \"{{ nummer }}\", \"text\": \"{{ nachricht }}\", \"session\": \"{{ sitzung }}\" }"
        content_type: 'application/json'

```
Content of the script:
```
sequence:
  - data_template:
      nummer: "{{nummer}}"
      nachricht: "{{nachricht}}"
      sitzung: default
    action: rest_command.whatsappsend
fields:
  nummer:
    selector:
      text: null
    required: true
    name: nummer
  nachricht:
    selector:
      text: null
    name: nachricht
    required: true
alias: whatsappmessage
description: ""

```
