### DISCUSSION TITLE
I want to host this on coolify but need help updating the compose file

### DISCUSSION THREAD

**Discussion by Nafalan** [devlikeapro/waha#740] [Q&A] [answered]
I've been tinkering with coolify and have deployed other apps but I'm having an issue because of the docker login stuff.

I did buy plus but I don't know how to parse the data so when I press deploy on the coolify dashboard it launches. I just get this error

Saved configuration files to /data/coolify/services/v8gowckwcww4ko4080o08400.
Creating Docker network.
Starting service.
Pulling images.
 waha Pulling 
 waha Error pull access denied for devlikeapro/waha-plus, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Error response from daemon: pull access denied for devlikeapro/waha-plus, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

I am able to run it on my machine locally without a problem but can't get it to work on my server.

Can I get some assistance with this deploy please?

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment, marked as answer]
Hi! Try following their docs, **Docker Credentials** guide
https://coolify.io/docs/knowledge-base/docker/registry/

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Reply by Nafalan** [reply]
Figured it out but I have a new problem.

The files/photos/videos I send can't be received  but it's a different issue.

I feel it's a problem with my compose file and env variables 

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Reply by devlikepro** [reply]
https://github.com/devlikeapro/waha/discussions/746 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by vargasjona** [comment]
Hi @Nafalan I used this one and worked

```yaml
services:
  waha:
    image: devlikeapro/waha:latest
    container_name: waha
    restart: unless-stopped
    shm_size: '512mb'
    cap_add:
      - SYS_ADMIN
    ports:
      - "3000:3000"
    volumes:
      - sessions:/app/.sessions
      - media:/app/.media
    environment:
      # ====================
      # ===== SECURITY =====
      # ====================
      - WAHA_API_KEY=${WAHA_API_KEY}
      - WAHA_API_KEY_PLAIN=${WAHA_API_KEY_PLAIN}
      - WAHA_DASHBOARD_USERNAME=${WAHA_DASHBOARD_USERNAME}
      - WAHA_DASHBOARD_PASSWORD=${WAHA_DASHBOARD_PASSWORD}
      - WHATSAPP_SWAGGER_USERNAME=${WAHA_DASHBOARD_USERNAME}
      - WHATSAPP_SWAGGER_PASSWORD=${WAHA_DASHBOARD_PASSWORD}
      - WAHA_DASHBOARD_ENABLED=True
      - WHATSAPP_SWAGGER_ENABLED=True

      # ====================
      # ===== URLS =========
      # ====================
      - WAHA_BASE_URL=${WAHA_BASE_URL}
      - WAHA_PUBLIC_URL=${WAHA_BASE_URL}

      # ====================
      # ===== ENGINE =======
      # ====================
      # GOWS = recomendado para Chatwoot App (más estable y ligero)
      # WEBJS = Chromium real (requiere shm_size 512mb y SYS_ADMIN)
      # NOWEB = Baileys (NO recomendado, mismo problema que Evolution API)
      - WHATSAPP_DEFAULT_ENGINE=${WHATSAPP_DEFAULT_ENGINE:-GOWS}

      # ====================
      # ===== SESSIONS =====
      # ====================
      - WAHA_PRINT_QR=False
      - WHATSAPP_RESTART_ALL_SESSIONS=True
      - WAHA_CLIENT_DEVICE_NAME=${WAHA_CLIENT_DEVICE_NAME:-WAHA}
      - WAHA_CLIENT_BROWSER_NAME=Chrome
      - WAHA_AUTO_START_DELAY_SECONDS=0

      # ====================
      # ===== STORAGE ======
      # ====================
      - WAHA_MEDIA_STORAGE=LOCAL
      - WHATSAPP_FILES_LIFETIME=0
      - WHATSAPP_FILES_FOLDER=/app/.media

      # ====================
      # ===== LOGGING ======
      # ====================
      - WAHA_LOG_FORMAT=JSON
      - WAHA_LOG_LEVEL=info
      - WAHA_PRINT_QR=False

      # ==========================
      # ===== CHATWOOT APP  ======
      # ==========================
      - WAHA_APPS_ENABLED=True
      - WAHA_APPS_ON=chatwoot
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - WAHA_CHATWOOT_COMMAND_PREFIX=wa/
      - WAHA_CHATWOOT_MESSAGE_CALENDAR_THRESHOLD_SECONDS=600

      # ==============================
      # ===== IGNORE CHATS  ==========
      # ==============================
      - WAHA_SESSION_CONFIG_IGNORE_STATUS=false
      - WAHA_SESSION_CONFIG_IGNORE_GROUPS=false
      - WAHA_SESSION_CONFIG_IGNORE_CHANNELS=true
      - WAHA_SESSION_CONFIG_IGNORE_BROADCAST=true

      # ==============================
      # ===== JOBS (BullMQ) ==========
      # ==============================
      - WAHA_APPS_JOBS_CONCURRENCY=50
      - WAHA_APPS_JOBS_ATTEMPTS=3
      - WAHA_APPS_JOBS_BACKOFF_TYPE=exponential
      - WAHA_APPS_JOBS_BACKOFF_DELAY=1000

    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  redis:
    image: redis:7-alpine
    container_name: waha_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sessions:
  media:
  redis_data:
```

environment variables
```bash
# ============================================================
# WAHA + Chatwoot - Variables de Entorno para Coolify
# Pegar en: Environment Variables → Developer View
# ============================================================
# Generar valores únicos con: uuidgen | tr -d '-'
# ============================================================

# ====================
# ===== SECURITY =====
# ====================
WAHA_API_KEY=44444444444444444444444444444444
WAHA_API_KEY_PLAIN=44444444444444444444444444444444
WAHA_DASHBOARD_USERNAME=admin
WAHA_DASHBOARD_PASSWORD=44444444444444444444444444444444
WHATSAPP_SWAGGER_USERNAME=admin
WHATSAPP_SWAGGER_PASSWORD=44444444444444444444444444444444
REDIS_PASSWORD=44444444444444444444444444444444

# ====================
# ===== URLS ==========
# ====================
# Tu dominio asignado en Coolify para WAHA
WAHA_BASE_URL=https://waha.allient.io

# ====================
# ===== ENGINE =======
# ====================
# GOWS  = recomendado para Chatwoot (estable, ligero)
# WEBJS = Chromium real (más RAM, requiere shm_size 512mb)
# NOWEB = Baileys (NO recomendado)
WHATSAPP_DEFAULT_ENGINE=GOWS

# ====================
# ===== DEVICE =======
# ====================
# Nombre visible en WhatsApp → Dispositivos vinculados
WAHA_CLIENT_DEVICE_NAME=Allient_Phone
```

<img width="1211" height="509" alt="image" src="https://github.com/user-attachments/assets/80cf5d5f-6c8a-4b18-836e-61f57b2e0964" />
<img width="1029" height="637" alt="image" src="https://github.com/user-attachments/assets/84157a93-eb38-4b37-a232-78208a27c199" />
