### DISCUSSION TITLE
Sessions not restored after worker recreation (even with MongoDB and session volume mounted)

### DISCUSSION THREAD

**Discussion by TitoBahe** [devlikeapro/waha#927] [Q&A]
Hi, I’m running the API in Docker with persistent storage using MongoDB. 
After rebuilding my worker containers, none of the WhatsApp sessions are restored — but the issue is even worse: I can’t scan the QR code again, and every worker (even new ones without any previous session) gets stuck in a loop error state spamming these next logs:

**To recriate this problem I suggest to change something on the docker compose file related to the waha service, recriate the container and send a mensage with the number previously connected, maybe the mesage will be sent normally, but right after the session disconnects.**   

```
noweb_4  | [13:36:46.952] ERROR (NOWEBEngine/1): session:xkCvZLdM9TSwxl5k36hU-clientId0 - stream errored out {"session":"xkCvZLdM9TSwxl5k36hU-clientId0","node":{"tag":"stream:error","attrs":{},"content":[{"tag":"conflict","attrs":{"type":"replaced"}}]}}
```
```
noweb_3  | [13:59:38.438] ERROR (NOWEBEngine/1): session:xkCvZLdM9TSwxl5k36hU-clientId0 - unexpected error in 'init queries' {"session":"xkCvZLdM9TSwxl5k36hU-clientId0"}
noweb_3  |     err: {
noweb_3  |       "tag": "stream:error",
noweb_3  |       "attrs": {},
noweb_3  |       "content": [
noweb_3  |         {
noweb_3  |           "tag": "conflict",
noweb_3  |           "attrs": {
noweb_3  |             "type": "replaced"
noweb_3  |           }
noweb_3  |         }
noweb_3  |       ]
noweb_3  |     }
```

```
noweb_4  | [14:01:52.425] INFO (NOWEBEngine/1): session:xkCvZLdM9TSwxl5k36hU-clientId0 - 27 pre-keys found on server {"session":"xkCvZLdM9TSwxl5k36hU-clientId0"}
noweb_2  | [14:01:52.254] DEBUG (WhatsappSession/1): session:xkCvZLdM9TSwxl5k36hU-clientId0 - Running job... {"session":"xkCvZLdM9TSwxl5k36hU-clientId0","job":"start-engine","class":"SingleDelayedJobRunner"}
noweb_2  | [14:01:52.255] INFO (WebhookSender/1): session:xkCvZLdM9TSwxl5k36hU-clientId0 - Sending POST... {"session":"xkCvZLdM9TSwxl5k36hU-clientId0","id":"01JSS6F4BZC1YHC2RD3WD1BPPP","event.id":"evt_01jss6f4bynyc0px1fz8ffvz11","url":"https://fullzapp.com/message"}
noweb_2  | [14:01:52.255] DEBUG (WebhookSender/1): session:xkCvZLdM9TSwxl5k36hU-clientId0 - POST DATA {"session":"xkCvZLdM9TSwxl5k36hU-clientId0","id":"01JSS6F4BZC1YHC2RD3WD1BPPP","event.id":"evt_01jss6f4bynyc0px1fz8ffvz11","url":"https://fullzapp.com/message"}
noweb_2  | [14:01:52.260] DEBUG (WhatsappSession/1): session:xkCvZLdM9TSwxl5k36hU-clientId0 - Connecting store... {"session":"xkCvZLdM9TSwxl5k36hU-clientId0"}
noweb_2  | [14:01:52.260] DEBUG (WhatsappSession/1): session:xkCvZLdM9TSwxl5k36hU-clientId0 - Binding store to socket... {"session":"xkCvZLdM9TSwxl5k36hU-clientId0"}
noweb_2  | [14:01:52.260] DEBUG (WhatsappSession/1): session:xkCvZLdM9TSwxl5k36hU-clientId0 - Start listening connection.update... {"session":"xkCvZLdM9TSwxl5k36hU-clientId0"}
noweb_2  | [14:01:52.260] DEBUG (WhatsappSession/1): session:xkCvZLdM9TSwxl5k36hU-clientId0 - Job finished {"session":"xkCvZLdM9TSwxl5k36hU-clientId0","job":"start-engine","class":"SingleDelayedJobRunner"}
noweb_2  | [14:01:52.260] DEBUG (WhatsappSession/1): session:xkCvZLdM9TSwxl5k36hU-clientId0 - NOWEB events {"session":"xkCvZLdM9TSwxl5k36hU-clientId0","events":{"connection.update":{"connection":"connecting","receivedPendingNotifications":false}}}
```

_Here's some screenshots made right after restarting the waha workers containers:_

![image](https://github.com/user-attachments/assets/8bde9b48-3e45-4816-8fe3-2718324447b0)

![image](https://github.com/user-attachments/assets/7f92432b-9ef0-48c2-acc5-803c09c5771f)

As you can see the sessions are saved in mongoDB. But I cant get new QR codes due to that error. 

I am using the latest WAHA version and this is my docker-compose.yml file, I have 4 waha workers follwing the horizntal scalling using the shardding technic that you guys recommend in the WAHA's blog:

 ```
 mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - fullzapp_network
    volumes:
      - mongo_data:/data/db
    ports:
      - '127.0.0.1:27017:27017/tcp'
    restart: always

 noweb_1:
    image: devlikeapro/waha-plus:noweb
    container_name: noweb_1
    environment:
      - WHATSAPP_DEFAULT_ENGINE=NOWEB
      - WHATSAPP_SESSIONS_MONGO_URL=mongodb://mongodb:27017/noweb1
    ports:
      - '127.0.0.1:3001:3000/tcp'
    networks:
      - fullzapp_network
    volumes:
      - './.media_1:/app/.media'
    restart: always
```

OBS: I just deleted the sessions prevously created and the "me" tab is still showing ,in mongodb-compass, a session that is not shown on sessions tab since all sessions were deleted, I thinks thats whats causing the errors above: 

![image](https://github.com/user-attachments/assets/a4d8bc7e-44b8-4401-b4ce-99b1c95702d4)

And the session tab:

![image](https://github.com/user-attachments/assets/d21f9bab-3c09-4362-b7e2-2018f4e6b98b)

EDIT:
What I just realized is that the **session_worker** subcollection in the **waha_noweb** collection is being **deleted** everytime I rebuild the container with a new image. I thinks it causes the disconnection, and since the cellphone number is still authenticated the **me** subcollection still outputs the session as being connected.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
