### DISCUSSION TITLE
Define an API base path?

### DISCUSSION THREAD

**Discussion by goleadev** [devlikeapro/waha#95] [Q&A]
Hello,

Is it possible to define a base path for the API? Currently, all API calls need to be made to http://localhost:3000 (e.g. http://localhost:3000/api/session/start). Is it possible to change this to something like http://localhost:3000/waha (e.g. http://localhost:3000/waha/api/session/start)?

**Comment by allburov** [comment]
Hi! It doesn't support it. You can run nginx close to the WAHA and proxy requests there

**Comment by allburov** [comment]
It may help:

**docker-compose.yaml**
```yaml
version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
  app:
    image: whatsapp-http-api
```
**nginx.conf**
```
worker_processes 1;

events { worker_connections 1024; }

http {
  server {
    listen 80;
    server_name localhost;

    location /waha/ {
      proxy_pass http://app:3000/api/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
```
docker-compose up
