### DISCUSSION TITLE
NOWEB Memory consumption ~ 10 GB

### DISCUSSION THREAD

**Discussion by manojsitapara** [devlikeapro/waha#984] [Q&A]
I am using WAHA in a Docker container with a PostgreSQL database, and I have 43 active sessions running inside the container. Each session is sending messages regularly to different WhatsApp groups.

The problem is – my WAHA container is using a lot of RAM – more than 9 GB! 

Can someone please help me or guide me on how I can reduce this high RAM usage? Any tips or best practices will be appreciated. 

My use case:
Each session sends frequent messages to many WhatsApp groups.

Here is my Docker Compose setup for WAHA:

```
waha1:
  image: devlikeapro/waha-plus:noweb
  container_name: waha-instance-3600
  restart: unless-stopped
  depends_on:
    postgres1:
      condition: service_healthy
  environment:
    WHATSAPP_SESSIONS_POSTGRESQL_URL: postgres://postgres:123456@postgres1:5432/postgres?sslmode=disable
    NODE_ENV: production
    X_API_KEY: 123456789
    WAHA_LOG_FORMAT: JSON
    WAHA_LOG_LEVEL: error
    NOWEB_MARK_ONLINE: "true"
    WHATSAPP_DOWNLOAD_MEDIA: "false"
    WHATSAPP_HOOK_URL: https://mywebsite.com
    WHATSAPP_HOOK_EVENTS: session.status
    WEBHOOK_RETRIES_ATTEMPTS: "5"
    WEBHOOK_RETRIES_DELAY_SECONDS: "10"
  volumes:
    - /var/WAHA/sessions_3600:/app/.sessions
  ports:
    - "3600:3000"
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "5"

```

And this is my session creation config:

```
payload = json.dumps({
    "name": normalize_email_address,
    "start": True,
    "config": {
        "metadata": {"user.email": email_address},
        "debug": False,
        "noweb": {
            "markOnline": True,
            "store": {
                "enabled": False,
                "fullSync": False
            }
        }
    }
})

```
Screenshot of docker stats output: 

![image](https://github.com/user-attachments/assets/4f0d7c70-e92f-4593-b98e-f831b4230ce2)

Thanks in advance for any help! 

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
